import PageShell from "./page-shell";
import { closingLine } from "./page-closing";
import StructuredData from "./structured-data";
import { legalMeta, legalPath, type LegalSection } from "./legal-sections";
import { contactEmail, enquiryCc, type Lang } from "./site-config";

type Section = { title: string; paragraphs?: readonly string[]; fields?: readonly (readonly [string, string])[] };
const company = "Jiashan Frankonia EMC Co., Ltd.";
const address = "No.55, Hongqiao Rd, Zone 4, Jiashan, Zhejiang 314100, China";
const sources = [
  ["中华人民共和国个人信息保护法 / Personal Information Protection Law", "https://www.cac.gov.cn/2021-08/20/c_1631050028355286.htm"],
  ["网络数据安全管理条例 / Network Data Security Management Regulations", "https://www.cac.gov.cn/2024-09/30/c_1729384452307680.htm"],
  ["促进和规范数据跨境流动规定 / Cross-border data flow provisions", "https://www.cac.gov.cn/2024-03/22/c_1712776611775634.htm"],
  ["非经营性互联网信息服务备案管理办法 / Non-commercial internet information service filing rules", "https://www.beijing.gov.cn/zhengce/zhengcefagui/qtwj/202308/t20230830_3236516.html"],
] as const;

const content: Record<Lang, Record<LegalSection, readonly Section[]>> = {
  zh: {
    imprint: [
      { title: "网站运营者", fields: [["网站", "https://www.emc-frankonia.com"], ["英文名称", company], ["营业执照登记的中文名称", "嘉善法兰克尼亚电磁兼容有限公司"], ["联系地址", "浙江省嘉善县惠民街道虹桥路 55 号"], ["法定注册地址", "浙江省嘉善县惠民街道虹桥路55号"], ["电话", "+86 573 8473 1555"], ["业务联系邮箱", contactEmail]] },
      { title: "企业登记与网站备案", fields: [["统一社会信用代码", "913304217570906770"], ["法定代表人", "沃夫刚·欧贝兹（Wolfgang Opitz）"], ["登记机关", "嘉善县市场监督管理局"], ["企业信用信息查询平台", "https://www.gsxt.gov.cn"], ["公司提供的既有ICP备案号", "浙ICP备14033841号"]], paragraphs: ["本网站由嘉善法兰克尼亚电磁兼容有限公司在中国运营，适用中华人民共和国法律。企业登记信息可通过国家企业信用信息公示系统查询；既有ICP备案的主体和域名范围以工业和信息化部备案系统记录为准。"] },
      { title: "网站使用", paragraphs: ["本网站提供 EMC 产品与服务信息。产品资料和选型结果供咨询参考，具体规格、交付与交易条件以双方确认的文件为准。网站询价清单不构成订单。", "网站内容、图片、商标及文件的权利归相应权利人所有。需要超出法律允许范围的使用，请联系权利人取得许可。外部链接网站由各自运营者负责。", "本声明不限制依法不得排除或限制的权利与责任。个人信息处理请参阅本网站隐私政策。"] },
    ],
    privacy: [
      { title: "1. 适用范围与联系方式", paragraphs: ["本政策适用于 www.emc-frankonia.com 的访问、产品选型与邮件询价，以《中华人民共和国个人信息保护法》及相关规定为依据。其他集团网站和您使用的邮件服务另有各自的政策。"], fields: [["个人信息处理者（英文名称）", company], ["登记中文名称", "嘉善法兰克尼亚电磁兼容有限公司"], ["联系地址", "浙江省嘉善县惠民街道虹桥路 55 号"], ["业务联系邮箱（可转交隐私请求）", contactEmail], ["个人信息保护联系人", "个人信息保护专员"], ["隐私请求邮箱", "chuck.zhang@emc-frankonia.com"], ["生效日期", "2026-09-10"]] },
      { title: "2. 网站访问与运行安全", paragraphs: ["访问网页时，您的浏览器会向网站托管服务发送网络请求，包括用于通信的 IP 地址和所请求的资源。相关技术信息用于提供网页、排查故障及保障运行安全。", "运行与安全记录的保存应限于实现上述目的所需的期限，并遵守适用的法定保存要求；达到删除条件后予以删除或匿名化。有关访问记录的查询、删除或其他个人信息请求，请联系本政策列明的个人信息保护专员。"] },
      { title: "3. 浏览器本地存储", paragraphs: ["当前网站代码未设置 Cookie，未接入广告跟踪、统计分析 SDK 或第三方嵌入式地图、视频；字体由网站自身提供。托管服务仍会接收访问请求。", "询价清单使用 localStorage（frankonia.jiashan.mycart.v1）保存所选产品、规格、配置、来源页面、语言和添加时间，以便在同一浏览器中继续选型。清单不会自动上传，没有自动到期时间；可在询价清单中清空或通过浏览器删除本站数据。联系表单字段不写入此清单存储。"] },
      { title: "4. 邮件询价", paragraphs: ["您填写的公司、联系人、邮箱、电话、项目要求、选型答案及备注，用于编写询价邮件。网站打开您的邮件程序，不直接向服务器提交表单；只有您实际发送邮件后，相应收件人才会收到内容。", `普通询价发往 ${contactEmail}。My Chamber 向导及问卷生成的邮件还会预填抄送收件人 ${enquiryCc}；发送前可在邮件程序查看、修改或删除收件人及正文。`, "邮件用于回复咨询、技术沟通及报价。根据公司提供的运营资料，邮件服务为阿里云企业邮箱，存储于中国内地；仅授权的销售、技术支持和行政人员在业务必要范围内访问。业务邮件在相关项目结束后保留五年，到期永久删除或匿名化；未形成项目的询价及非业务邮件仅在完成回复、必要跟进或履行法定义务所需期间保留，目的实现且无继续保存的合法必要时删除或匿名化。上述五年为公司提供的业务规则，并非所有邮件的法定统一期限；依法应提前删除或另有法定保存要求的，从其规定。请勿在询价中提供身份证件、金融账户、健康信息等无关敏感信息。"] },
      { title: "5. 处理依据与选择", paragraphs: ["各项处理须具备适用的法定依据；依赖同意时，您可撤回同意；依法需要单独同意的事项应单独办理。浏览本政策不等于同意所有处理。", "仅在为订立、履行个人作为一方当事人的合同所必需时，适用该合同处理依据；企业联系人询价不能一概按此处理。依赖同意时，应先告知目的、方式、信息种类等并取得自愿、明确的同意，不将主动发送邮件一概视为有效同意。履行网络安全等法定义务所必需的处理以相应法律规定为依据；不属于法定免同意情形的处理，应依法取得同意。可通过隐私请求邮箱撤回同意。不发送询价邮件不影响浏览产品资料，但我们无法回复未收到的询价。"] },
      { title: "6. 服务提供商与境外联系", paragraphs: ["本网站通过网站托管服务提供页面，并使用阿里云企业邮箱处理业务邮件。我们向服务提供商提供个人信息时，应限定于服务所必需的范围，并依法明确其处理目的、期限及安全保护义务。", `My Chamber 邮件会预填集团邮箱 ${enquiryCc} 为抄送收件人，用于技术询价协作。请在发送前检查收件人；如希望仅联系嘉善公司，可删除该抄送并发送至 ${contactEmail}。`, "涉及向境外提供个人信息时，应在提供前依法告知接收方、处理目的、方式、信息种类及权利行使途径，履行适用的单独同意、影响评估和出境手续。上述义务以中国法律为准，本政策不替代具体的出境告知或同意程序。有关境外联系和权利请求，请联系个人信息保护专员。"] },
      { title: "7. 您的权利", paragraphs: ["您可依法请求查阅、复制、更正、补充、删除个人信息，限制或拒绝处理、撤回同意，并在符合规定条件时请求转移；也可要求解释处理规则。", `可向 chuck.zhang@emc-frankonia.com 提交请求，也可通过 ${contactEmail} 转交，说明请求事项及便于回复的联系方式。我们通过将您提供的信息与已有业务记录比对进行身份核验，并按公司提供的流程在身份核验后十五个工作日内答复；该期限为公司承诺，不代表法定统一期限。我们会及时受理请求，不以不合理的核验要求拖延处理。请勿主动发送完整身份证件。网站没有注册账户，无需办理网站账号注销。`, "对处理结果有异议，可向履行个人信息保护职责的部门投诉、举报，或依法寻求司法救济。您可通过浙江省互联网信息办公室或其他有权部门公布的官方渠道反映个人信息保护问题。"] },
      { title: "8. 未成年人、安全与更新", paragraphs: ["本网站面向企业专业用户，不要求提供儿童资料。根据公司提供的处理规则，我们不主动收集不满十四周岁儿童的个人信息；如意外收到，将及时核实并删除。可通过隐私请求邮箱报告此类情况。", "网站通过 HTTPS 提供页面。公司提供的业务系统措施包括基于角色的访问控制、TLS 传输加密、静态数据加密及访问审计日志。上述说明针对公司的邮件和业务系统，不代表已核实所有外部服务的配置。达到删除条件时，我们将删除或匿名化相关信息；依法须保留或技术上暂时无法删除的，除必要存储和安全保护外停止处理。发生个人信息安全事件时，应依法采取补救和通知措施。", "政策版本更新日期：2026-09-11。后续处理方式变化应同步更新告知；依法需要重新取得同意时，应在相关处理前办理。"] },
    ],
  },
  en: {
    imprint: [
      { title: "Website operator", fields: [["Website", "https://www.emc-frankonia.com"], ["English name", company], ["Chinese name on business licence", "嘉善法兰克尼亚电磁兼容有限公司"], ["Contact address", address], ["Registered address", "No.55, Hongqiao Rd, Huimin Street, Jiashan, Zhejiang 314100, China"], ["Telephone", "+86 573 8473 1555"], ["Business email", contactEmail]] },
      { title: "Company registration and website filings", fields: [["Unified Social Credit Code", "913304217570906770"], ["Legal representative", "Wolfgang Opitz"], ["Registration authority", "Jiashan County Administration for Market Regulation"], ["Enterprise credit information search", "https://www.gsxt.gov.cn"], ["Existing ICP number supplied by the company", "浙ICP备14033841号"]], paragraphs: ["This website is operated in China by Jiashan Frankonia EMC Co., Ltd. and is governed by the laws of the People’s Republic of China. Company registration information can be searched in the National Enterprise Credit Information Publicity System. The entity and domains covered by the existing ICP filing are determined by the Ministry of Industry and Information Technology filing records."] },
      { title: "Website use", paragraphs: ["This site provides EMC product and service information. Product materials and selection results support enquiries; specifications, delivery and commercial terms are subject to documents agreed by the parties. The enquiry list is not an order.", "Content, images, trademarks and documents belong to their respective rights holders. Obtain permission for uses beyond those permitted by law. Linked sites are operated by their respective providers.", "This notice does not exclude rights or liabilities that cannot lawfully be excluded. See this site's Privacy Policy for personal information processing."] },
    ],
    privacy: [
      { title: "1. Scope and contact", paragraphs: ["This policy applies to visits, product selection and email enquiries at www.emc-frankonia.com, with reference to China's Personal Information Protection Law and related rules. Other group sites and your email service have their own policies."], fields: [["Personal information handler (English name)", company], ["Registered Chinese name", "嘉善法兰克尼亚电磁兼容有限公司"], ["Contact address", address], ["Business email (can forward privacy requests)", contactEmail], ["Privacy contact", "Privacy Officer"], ["Privacy request email", "chuck.zhang@emc-frankonia.com"], ["Effective date", "2026-09-10"]] },
      { title: "3. Browser storage", paragraphs: ["The current website code sets no cookies and includes no advertising trackers, analytics SDKs or embedded third-party maps/videos. Fonts are served with the site. The host still receives page requests.", "The enquiry list uses localStorage (frankonia.jiashan.mycart.v1) for selected products, specifications, configurations, source pages, language and addition times, so you can continue selection in the same browser. It is not automatically uploaded and has no automatic expiry. Clear the enquiry list or delete this site's browser data to remove it. Contact form fields are not written to this list storage."] },
      { title: "4. Email enquiries", paragraphs: ["Company, contact name, email, telephone, project requirements, selection answers and notes populate an enquiry email. The website opens your mail program without submitting a form to a server. Recipients receive the content only when you send the email.", `Ordinary enquiries go to ${contactEmail}. My Chamber wizard and questionnaire emails also prefill ${enquiryCc} as a CC recipient. You can review, change or remove recipients and content in your mail program before sending.`, "Emails support responses, technical discussions and quotations. According to company-supplied operational information, Alibaba Cloud Enterprise Mail stores mail in mainland China. Access is limited to authorized sales, technical support and administrative staff for necessary business purposes. Business emails are retained for five years after the relevant project ends, then permanently deleted or anonymized. Enquiries that do not become projects and non-business emails are retained only as needed to respond, complete necessary follow-up or meet legal obligations, then deleted or anonymized when no lawful need for continued retention remains. The five-year period is a company rule, not a universal statutory requirement; earlier deletion duties or other statutory retention requirements take precedence. Please do not include unrelated sensitive information such as identity documents, financial accounts or health information."] },
      { title: "5. Processing grounds and choices", paragraphs: ["Each processing activity needs an applicable legal basis. Consent can be withdrawn where processing relies on it; matters requiring separate consent need a separate process. Reading this policy does not constitute consent to all processing.", "The contract basis applies only where necessary to enter into or perform a contract to which the individual is a party; it does not automatically cover every business contact enquiry. Where relying on consent, provide prior notice and obtain voluntary, explicit consent rather than treating every sent email as valid consent. Processing necessary to fulfil statutory duties, including applicable network security duties, relies on the relevant law. Consent must be obtained for processing that does not qualify for a statutory exception. You may withdraw consent through our privacy request email. Choosing not to send an enquiry does not prevent browsing, but we cannot answer an enquiry we have not received."] },
      { title: "6. Service providers and overseas contact", paragraphs: ["We use website hosting services to deliver pages and Alibaba Cloud Enterprise Mail for business correspondence. Personal information provided to service providers must be limited to what is necessary for the service, with processing purposes, duration and safeguards defined as required by law.", `My Chamber emails prefill the group mailbox ${enquiryCc} as a CC recipient for technical enquiry collaboration. Review recipients before sending. To contact only the Jiashan company, remove the CC and send to ${contactEmail}.`, "Before providing personal information overseas, applicable Chinese law requires notice of the recipient, purposes, methods, information categories and rights channels, together with applicable separate consent, impact assessment and transfer procedures. This policy does not replace a specific transfer notice or consent process. Contact our Privacy Officer about overseas contact or related rights requests."] },
      { title: "7. Your rights", paragraphs: ["Subject to law, you can request access, copies, correction, supplementation, deletion, restriction or refusal of processing, withdrawal of consent, conditional transfer, and explanation of processing rules.", `You may send a request to chuck.zhang@emc-frankonia.com or ask ${contactEmail} to forward it, describing it and providing reply details. We verify identity by matching supplied details against existing business records and, under the company-provided procedure, respond within 15 working days after verification. This is a company commitment, not a universal statutory deadline. Requests will be accepted promptly without unreasonable verification requirements that delay handling. Do not proactively send complete identity documents. This site has no registered accounts to close.`, "You may complain or report concerns to competent personal information protection authorities or seek judicial relief. You may raise personal information concerns through the official channels published by the Zhejiang Provincial Cyberspace Administration or another competent authority."] },
      { title: "8. Minors, security and updates", paragraphs: ["This site serves business professionals and does not request children's information. Under the company-provided handling rule, we do not actively collect information about children under 14 and will promptly verify and delete it if received accidentally. Please report such cases to the privacy request email.", "Pages are served over HTTPS. Company-supplied business-system measures include role-based access control, TLS in transit, encryption at rest and access audit logs. These describe the company’s email and business systems and do not verify all external providers’ configurations. When deletion conditions are met, we delete or anonymize the information. If retention is required by law or deletion is temporarily technically impracticable, processing is limited to necessary storage and security protection. Personal information incidents require remedial action and notification as applicable by law.", "Policy revision date: 2026-09-11. Changes in processing should be reflected in updated notices; renewed consent, where required, must precede the relevant processing."] },
    ],
  },
};

export default function LegalPage({ lang, section }: { lang: Lang; section: LegalSection }) {
  const { label, description } = legalMeta[lang][section];
  return (
    <PageShell lang={lang} eyebrow={section === "imprint" ? "IMPRINT" : "PRIVACY"} title={label}
      intro={lang === "zh" ? "本网站由嘉善法兰克尼亚电磁兼容有限公司在中国运营。本页介绍企业信息及依据中华人民共和国法律制定的个人信息处理规则。" : "This website is operated in China by Jiashan Frankonia EMC Co., Ltd. This page provides company information and personal information handling rules under the laws of the People’s Republic of China."}
      closing={closingLine(lang, legalPath(section))}>
      <StructuredData lang={lang} page="path" path={legalPath(section)} trail={[{ name: label, path: legalPath(section) }]} description={description} />
      {content[lang][section].map((item, index) => (
        <section key={item.title} className={index % 2 ? "alt" : undefined}><div className="wrap">
          <div className="sec-head"><h2>{item.title}</h2></div>
          {item.fields && <div className="hairline-list">{item.fields.map(([name, value]) => (
            <div className="hl-row hl-row--name" key={name}><b>{name}</b><span className="hl-desc">{value.includes("@") ? <a href={`mailto:${value}`}>{value}</a> : value.startsWith("https://") ? <a href={value} target="_blank" rel="noopener noreferrer">{value}</a> : value}</span></div>
          ))}</div>}
          {item.paragraphs && <div className="prose">{item.paragraphs.map(p => <p key={p}>{p}</p>)}</div>}
        </div></section>
      ))}
      <section><div className="wrap"><div className="sec-head"><h2>{lang === "zh" ? "参考资料" : "References"}</h2></div>
        <div className="prose"><ul>{sources.filter((_, i) => section === "privacy" ? i !== 3 : i === 3).map(([title, href]) => <li key={href}><a href={href} target="_blank" rel="noopener noreferrer">{title}</a></li>)}</ul></div>
      </div></section>
    </PageShell>
  );
}
